{% set name = "ocaml-num" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ocaml/num/archive/v{{ version }}.tar.gz
  sha256: 4f79c30e81ea9553c5b2c5b5b57bb19968ccad1e85256b3c446b5df58f33e94d

build:
  number: 0
  skip: True  # [win]

requirements:
  host:
    - ocaml
    - ocaml-findlib
  run:
    - ocaml

test:
  commands:
    - test -f ${PREFIX}/lib/ocaml/num.cmi

about:
  home: https://github.com/ocaml/num
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'The legacy Num library for arbitrary-precision integer and rational arithmetic for OCaml'
  doc_url: https://hal.inria.fr/file/index/docid/70027/filename/RT-0141.pdf
  dev_url: https://github.com/ocaml/num

extra:
  recipe-maintainers:
    - isuruf
    - slel
